name: 'kernel-info-action'
description: 'retrieve the current kernel versions by category'

inputs:
  base-url:
    description: "base url of the kernel-info deployment"
    required: false
    default: 'https://kernel.manjaro.download'

outputs:
  longterm:
    description: "latest longterm version"
    value: ${{ steps.receive.outputs.longterm }}
  longterm-pkg:
    description: "latest longterm package version"
    value: ${{ steps.receive.outputs.longterm-pkg }}
  stable:
    description: "latest stable version"
    value: ${{ steps.receive.outputs.stable }}
  stable-pkg:
    description: "latest stable package version"
    value: ${{ steps.receive.outputs.stable-pkg }}
  mainline:
    description: "latest mainline version"
    value: ${{ steps.receive.outputs.mainline }}
  mainline-pkg:
    description: "latest mainline package version"
    value: ${{ steps.receive.outputs.mainline-pkg }}

runs:
  using: "composite"
  steps:
    - id: receive
      shell: bash
      env:
        BASE_URL: ${{ inputs.base-url }}
      run: |
        set -euo pipefail

        for CATEGORY in longterm stable mainline; do
          PAYLOAD=$(curl -sSf "${BASE_URL%/}/category/${CATEGORY}.json" | jq '.[0]')
          echo "${CATEGORY}=$(echo "$PAYLOAD" | jq -r '.version')" >> $GITHUB_OUTPUT
          echo "${CATEGORY}-pkg=$(echo "$PAYLOAD" | jq -r '.packageName')" >> $GITHUB_OUTPUT
        done

    - id: list
      shell: bash
      run: |
        echo longterm: ${{ steps.receive.outputs.longterm }} - ${{ steps.receive.outputs.longterm-pkg }}
        echo stable: ${{ steps.receive.outputs.stable }} - ${{ steps.receive.outputs.stable-pkg }}
        echo mainline: ${{ steps.receive.outputs.mainline }} - ${{ steps.receive.outputs.mainline-pkg }}
